# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firt.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 1011)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(400, 0, 881, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(28)
        self.Title.setFont(font)
        self.Title.setTextFormat(QtCore.Qt.AutoText)
        self.Title.setObjectName("Title")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(240, 100, 951, 871))
        self.scrollArea.setMinimumSize(QtCore.QSize(591, 500))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 998))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 90, 191, 541))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 181, 511))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.BOPPD = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.BOPPD.setFont(font)
        self.BOPPD.setObjectName("BOPPD")
        self.vboxlayout.addWidget(self.BOPPD)
        self.CPPD = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.CPPD.setFont(font)
        self.CPPD.setObjectName("CPPD")
        self.vboxlayout.addWidget(self.CPPD)
        self.BOPETD = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.BOPETD.setFont(font)
        self.BOPETD.setObjectName("BOPETD")
        self.vboxlayout.addWidget(self.BOPETD)
        self.PPDFHZ = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.PPDFHZ.setFont(font)
        self.PPDFHZ.setObjectName("PPDFHZ")
        self.vboxlayout.addWidget(self.PPDFHZ)
        self.PPZSH = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.PPZSH.setFont(font)
        self.PPZSH.setObjectName("PPZSH")
        self.vboxlayout.addWidget(self.PPZSH)
        self.PEZSH = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.PEZSH.setFont(font)
        self.PEZSH.setObjectName("PEZSH")
        self.vboxlayout.addWidget(self.PEZSH)
        self.ICIS = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.ICIS.setFont(font)
        self.ICIS.setObjectName("ICIS")
        self.vboxlayout.addWidget(self.ICIS)
        self.Title.raise_()
        self.groupBox.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1344, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "塑膜网爬取数据分析"))
        self.BOPPD.setText(_translate("MainWindow", "BOPP日评"))
        self.CPPD.setText(_translate("MainWindow", "CPP日评"))
        self.BOPETD.setText(_translate("MainWindow", "BOPET日评"))
        self.PPDFHZ.setText(_translate("MainWindow", "PP地方/合资"))
        self.PPZSH.setText(_translate("MainWindow", "PP中石化"))
        self.PEZSH.setText(_translate("MainWindow", "PE中石化"))
        self.ICIS.setText(_translate("MainWindow", "ICIS PP BOPP"))

